### ISSUE TITLE
[Feature Request] use `aws_sdk_s3::Config` to initialize `S3Reader`

### ISSUE THREAD

**Issue by zerolfx** [anergictcell/s3reader#1]
Currently, `S3Reader` can be built from `aws_config::SdkConfig`. Supporting `aws_sdk_s3::Config` is useful because user can't configure path style in `aws_config::SdkConfig`.

Here is an example with path style configured.
```rust
let config = aws_sdk_s3::Config::builder()
    .endpoint_url(endpoint_url).force_path_style(true).behavior_version_latest().region(Region::new("us-east-1"))
    .build();
```

**Comment by anergictcell** [comment]
Hey @zerolfx : I added a new method `from_s3_config` to `S3Reader`. So it should work now.

Cheers
